### PR TITLE
fix: add automatic yes for apt-get calls

### LINKED ISSUE #38: Installing packages freezes in a self-hosted runner
Hi,

I'm trying to run end-to-end tests using Playwright on a self-hosted Ubuntu 18.04 runner. However, this action hangs when installing packages via APT (see output below) since it's waiting for the user to press <kbd>Y</kbd>.

It seems this is caused by missing `-y` flag in command `/usr/bin/sudo apt-get install --no-install-recommends ...`. Should it be appended to the command?

```
Run microsoft/playwright-github-action@v1
/usr/bin/sudo apt-get update
Hit:1 http://azure.archive.ubuntu.com/ubuntu bionic InRelease
Get:2 http://azure.archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:3 http://azure.archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
Hit:4 http://security.ubuntu.com/ubuntu bionic-security InRelease
Fetched 163 kB in 1s (247 kB/s)
Reading package lists...
/usr/bin/sudo apt-get install --no-install-recommends libasound2 libatk-bridge2.0-0 libatk1.0-0 libatspi2.0-0 libcairo2 libcups2 libdbus-1-3 libdrm2 libgbm1 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libnss3 libpango-1.0-0 libpangocairo-1.0-0 libx11-6 libx11-xcb1 libxcb-dri3-0 libxcb1 libxcomposite1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxtst6 libatk1.0-0 libcairo-gobject2 libcairo2 libdbus-1-3 libdbus-glib-1-2 libfontconfig1 libfreetype6 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libgtk2.0-0 libpango-1.0-0 libpangocairo-1.0-0 libpangoft2-1.0-0 libx11-6 libx11-xcb1 libxcb-shm0 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrender1 libxt6 gstreamer1.0-libav gstreamer1.0-plugins-bad gstreamer1.0-plugins-base gstreamer1.0-plugins-good libatk-bridge2.0-0 libatk1.0-0 libbrotli1 libcairo2 libegl1 libenchant1c2a libepoxy0 libfontconfig1 libfreetype6 libgdk-pixbuf2.0-0 libgl1 libgles2 libglib2.0-0 libgstreamer-gl1.0-0 libgstreamer1.0-0 libgtk-3-0 libharfbuzz-icu0 libharfbuzz0b libhyphen0 libicu60 libjpeg-turbo8 libnotify4 libopenjp2-7 libopus0 libpango-1.0-0 libpng16-16 libsecret-1-0 libvpx5 libwayland-client0 libwayland-egl1 libwayland-server0 libwebp6 libwebpdemux2 libwoff1 libx11-6 libxcomposite1 libxdamage1 libxkbcommon0 libxml2 libxslt1.1
Reading package lists...
Building dependency tree...
Reading state information...
libxext6 is already the newest version (2:1.3.3-1).
libxext6 set to manually installed.
libcups2 is already the newest version (2.2.7-1ubuntu2.8).
libdbus-1-3 is already the newest version (1.12.2-1ubuntu1.2).
libdbus-1-3 set to manually installed.
libdrm2 is already the newest version (2.4.101-2~18.04.1).
libdrm2 set to manually installed.
libfreetype6 is already the newest version (2.8.1-2ubuntu2.1).
libfreetype6 set to manually installed.
libglib2.0-0 is already the newest version (2.56.4-0ubuntu0.18.04.6).
libglib2.0-0 set to manually installed.
libicu60 is already the newest version (60.2-3ubuntu3.1).
libicu60 set to manually installed.
libpng16-16 is already the newest version (1.6.34-1ubuntu0.18.04.2).
libpng16-16 set to manually installed.
libx11-6 is already the newest version (2:1.6.4-3ubuntu0.3).
libx11-6 set to manually installed.
libxcb1 is already the newest version (1.13-2~ubuntu18.04).
libxcb1 set to manually installed.
libxml2 is already the newest version (2.9.4+dfsg1-6.1ubuntu1.3).
libxml2 set to manually installed.
libxslt1.1 is already the newest version (1.1.29-5ubuntu0.2).
libxslt1.1 set to manually installed.
The following package was automatically installed and is no longer required:
  linux-headers-4.15.0-124
Use 'sudo apt autoremove' to remove it.
The following additional packages will be installed:
  adwaita-icon-theme aspell aspell-en dconf-gsettings-backend dconf-service
  dictionaries-common emacsen-common fontconfig fontconfig-config
  fonts-dejavu-core glib-networking glib-networking-common
  glib-networking-services gsettings-desktop-schemas gtk-update-icon-cache
  hicolor-icon-theme humanity-icon-theme libaa1 libasound2-data libaspell15
  libass9 libasyncns0 libatk1.0-data libavc1394-0 libavcodec57 libavfilter6
  libavformat57 libavresample3 libavutil55 libbluray2 libbs2b0 libcaca0
  libcdparanoia0 libchromaprint1 libcolord2 libcroco3 libcrystalhd3 libdatrie1
  libdc1394-22 libdca0 libdconf1 libde265-0 libdrm-amdgpu1 libdrm-intel1
  libdrm-nouveau2 libdrm-radeon1 libdv4 libdvdnav4 libdvdread4 libegl-mesa0
  libfaad2 libfftw3-double3 libflac8 libflite1 libfluidsynth1
  libgdk-pixbuf2.0-common libgl1-mesa-dri libglapi-mesa libglvnd0 libglx-mesa0
  libglx0 libgme0 libgomp1 libgraphite2-3 libgsm1 libgssdp-1.0-3
  libgstreamer-plugins-bad1.0-0 libgstreamer-plugins-base1.0-0
  libgstreamer-plugins-good1.0-0 libgtk-3-common libgtk2.0-common
  libgudev-1.0-0 libgupnp-1.0-4 libgupnp-igd-1.0-4 libhunspell-1.6-0 libice6
  libiec61883-0 libilmbase12 libjack-jackd2-0 libjbig0 libjpeg8
  libjson-glib-1.0-0 libjson-glib-1.0-common libkate1 liblcms2-2 liblilv-0-0
  libllvm10 libmjpegutils-2.1-0 libmms0 libmodplug1 libmp3lame0 libmpcdec6
  libmpeg2encpp-2.1-0 libmpg123-0 libmplex2-2.1-0 libmysofa0 libnice10
  libnorm1 libofa0 libogg0 libopenal-data libopenal1 libopenexr22 libopenmpt0
  liborc-0.4-0 libpciaccess0 libpgm-5.2-0 libpixman-1-0 libpostproc54
  libproxy1v5 libpulse0 libraw1394-11 librest-0.7-0 librsvg2-2 librsvg2-common
  librubberband2 libsamplerate0 libsbc1 libsecret-common libsensors4
  libserd-0-0 libshine3 libshout3 libsm6 libsnappy1v5 libsndfile1 libsndio6.1
  libsodium23 libsord-0-0 libsoundtouch1 libsoup-gnome2.4-1 libsoup2.4-1
  libsoxr0 libspandsp2 libspeex1 libsratom-0-0 libsrtp2-1 libssh-gcrypt-4
  libswresample2 libswscale4 libtag1v5 libtag1v5-vanilla libthai-data libthai0
  libtheora0 libtiff5 libtwolame0 libv4l-0 libv4lconvert0 libva-drm2
  libva-x11-2 libva2 libvdpau1 libvisual-0.4-0 libvo-aacenc0 libvo-amrwbenc0
  libvorbis0a libvorbisenc2 libvorbisfile3 libvulkan1 libwavpack1
  libwayland-cursor0 libwebpmux3 libwebrtc-audio-processing1
  libwildmidi-config libwildmidi2 libx264-152 libx265-146 libxcb-dri2-0
  libxcb-glx0 libxcb-present0 libxcb-render0 libxcb-sync1 libxcb-xfixes0
  libxinerama1 libxshmfence1 libxvidcore4 libxxf86vm1 libzbar0 libzmq5
  libzvbi-common libzvbi0 ubuntu-mono x11-common
Suggested packages:
  aspell-doc spellutils wordlist frei0r-plugins gvfs libasound2-plugins
  alsa-utils libbluray-bdj colord firmware-crystalhd libdv-bin oss-compat
  libdvdcss2 libenchant-voikko libfftw3-bin libfftw3-dev
  fluidr3mono-gm-soundfont | timgm6mb-soundfont | fluid-soundfont-gm
  libvisual-0.4-plugins gstreamer1.0-tools jackd2 liblcms2-utils libportaudio2
  opus-tools pulseaudio libraw1394-doc librsvg2-bin lm-sensors serdi sndiod
  sordi speex
Recommended packages:
  gstreamer1.0-x at-spi2-core libaacs0 enchant libgdk-pixbuf2.0-bin
  gstreamer1.0-gl libgtk-3-bin libgail-common libgtk2.0-bin hunspell-en-us
  | hunspell-dictionary | myspell-dictionary notification-daemon va-driver-all
  | va-driver vdpau-driver-all | vdpau-driver freepats
The following NEW packages will be installed:
  adwaita-icon-theme aspell aspell-en dconf-gsettings-backend dconf-service
  dictionaries-common emacsen-common fontconfig fontconfig-config
  fonts-dejavu-core glib-networking glib-networking-common
  glib-networking-services gsettings-desktop-schemas gstreamer1.0-libav
  gstreamer1.0-plugins-bad gstreamer1.0-plugins-base gstreamer1.0-plugins-good
  gtk-update-icon-cache hicolor-icon-theme humanity-icon-theme libaa1
  libasound2 libasound2-data libaspell15 libass9 libasyncns0
  libatk-bridge2.0-0 libatk1.0-0 libatk1.0-data libatspi2.0-0 libavc1394-0
  libavcodec57 libavfilter6 libavformat57 libavresample3 libavutil55
  libbluray2 libbrotli1 libbs2b0 libcaca0 libcairo-gobject2 libcairo2
  libcdparanoia0 libchromaprint1 libcolord2 libcroco3 libcrystalhd3 libdatrie1
  libdbus-glib-1-2 libdc1394-22 libdca0 libdconf1 libde265-0 libdrm-amdgpu1
  libdrm-intel1 libdrm-nouveau2 libdrm-radeon1 libdv4 libdvdnav4 libdvdread4
  libegl-mesa0 libegl1 libenchant1c2a libepoxy0 libfaad2 libfftw3-double3
  libflac8 libflite1 libfluidsynth1 libfontconfig1 libgbm1 libgdk-pixbuf2.0-0
  libgdk-pixbuf2.0-common libgl1 libgl1-mesa-dri libglapi-mesa libgles2
  libglvnd0 libglx-mesa0 libglx0 libgme0 libgomp1 libgraphite2-3 libgsm1
  libgssdp-1.0-3 libgstreamer-gl1.0-0 libgstreamer-plugins-bad1.0-0
  libgstreamer-plugins-base1.0-0 libgstreamer-plugins-good1.0-0
  libgstreamer1.0-0 libgtk-3-0 libgtk-3-common libgtk2.0-0 libgtk2.0-common
  libgudev-1.0-0 libgupnp-1.0-4 libgupnp-igd-1.0-4 libharfbuzz-icu0
  libharfbuzz0b libhunspell-1.6-0 libhyphen0 libice6 libiec61883-0
  libilmbase12 libjack-jackd2-0 libjbig0 libjpeg-turbo8 libjpeg8
  libjson-glib-1.0-0 libjson-glib-1.0-common libkate1 liblcms2-2 liblilv-0-0
  libllvm10 libmjpegutils-2.1-0 libmms0 libmodplug1 libmp3lame0 libmpcdec6
  libmpeg2encpp-2.1-0 libmpg123-0 libmplex2-2.1-0 libmysofa0 libnice10
  libnorm1 libnotify4 libnspr4 libnss3 libofa0 libogg0 libopenal-data
  libopenal1 libopenexr22 libopenjp2-7 libopenmpt0 libopus0 liborc-0.4-0
  libpango-1.0-0 libpangocairo-1.0-0 libpangoft2-1.0-0 libpciaccess0
  libpgm-5.2-0 libpixman-1-0 libpostproc54 libproxy1v5 libpulse0 libraw1394-11
  librest-0.7-0 librsvg2-2 librsvg2-common librubberband2 libsamplerate0
  libsbc1 libsecret-1-0 libsecret-common libsensors4 libserd-0-0 libshine3
  libshout3 libsm6 libsnappy1v5 libsndfile1 libsndio6.1 libsodium23
  libsord-0-0 libsoundtouch1 libsoup-gnome2.4-1 libsoup2.4-1 libsoxr0
  libspandsp2 libspeex1 libsratom-0-0 libsrtp2-1 libssh-gcrypt-4
  libswresample2 libswscale4 libtag1v5 libtag1v5-vanilla libthai-data libthai0
  libtheora0 libtiff5 libtwolame0 libv4l-0 libv4lconvert0 libva-drm2
  libva-x11-2 libva2 libvdpau1 libvisual-0.4-0 libvo-aacenc0 libvo-amrwbenc0
  libvorbis0a libvorbisenc2 libvorbisfile3 libvpx5 libvulkan1 libwavpack1
  libwayland-client0 libwayland-cursor0 libwayland-egl1 libwayland-server0
  libwebp6 libwebpdemux2 libwebpmux3 libwebrtc-audio-processing1
  libwildmidi-config libwildmidi2 libwoff1 libx11-xcb1 libx264-152 libx265-146
  libxcb-dri2-0 libxcb-dri3-0 libxcb-glx0 libxcb-present0 libxcb-render0
  libxcb-shm0 libxcb-sync1 libxcb-xfixes0 libxcomposite1 libxcursor1
  libxdamage1 libxfixes3 libxi6 libxinerama1 libxkbcommon0 libxrandr2
  libxrender1 libxshmfence1 libxt6 libxtst6 libxvidcore4 libxxf86vm1 libzbar0
  libzmq5 libzvbi-common libzvbi0 ubuntu-mono x11-common
0 upgraded, 241 newly installed, 0 to remove and 25 not upgraded.
Need to get 83.2 MB of archives.
After this operation, 531 MB of additional disk space will be used.
Do you want to continue? [Y/n]
```

### PR DESCRIPTION
**Pull request by mxschmitt**
Fixes #38

since no package-lock file exists, it automatically installed a more recent version of the libs and thats why the dist file looks a bit different.

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -232,15 +232,15 @@ async function run() {
         deps = DEPENDENCIES['ubuntu20.04'];
       else
         throw new Error('Cannot install dependencies for this linux distribution!');
-      await exec('sudo', ['apt-get', 'install', '--no-install-recommends',
+      await exec('sudo', ['apt-get', 'install', '-y', '--no-install-recommends',
```
Comment (nikoheikkila) [inline index.js:235]: Thanks for the quick fix. Looks good to me. 👍🏼

**Review by arjunattam — APPROVED** [review]
Thanks @mxschmitt!
